/*
MIT License

Copyright (c) 2022 Philip Näf <philip.naef@amanda-technology.ch>
Copyright (c) 2022 Manuel Gysin <manuel.gysin@amanda-technology.ch>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

namespace BexioApiNet.Abstractions.Models.Purchases.PurchaseOrders;

/// <summary>
/// Purchase order entity returned by the Bexio v3.0 <c>/purchase_orders</c> endpoints
/// (GET list/by id, POST create, PUT <c>/{id}</c> update). Optional fields default to
/// <see langword="null"/>; only fields populated by the Bexio response are deserialized.
/// <see href="https://docs.bexio.com/#tag/Purchase-Orders">Purchase Orders</see>
/// </summary>
/// <param name="Id">Unique purchase order identifier (read-only).</param>
/// <param name="DocumentNr">Purchase order document number (e.g. <c>RE-00001</c>). Auto-generated by Bexio when omitted on create.</param>
/// <param name="ContactId">Identifier of the supplier contact the order is addressed to.</param>
/// <param name="UserId">Identifier of the user that owns the purchase order.</param>
/// <param name="CurrencyId">Identifier of the currency in which the order is denominated.</param>
/// <param name="LanguageId">Reference to a language object.</param>
/// <param name="BankAccountId">Reference to a bank account object.</param>
/// <param name="PaymentTypeId">Reference to a payment type object.</param>
/// <param name="LogopaperId">Reference to a logo-paper object.</param>
/// <param name="ContactSubId">Optional additional contact reference (e.g. addressee within the supplier company).</param>
/// <param name="ProjectId">Reference to a project object.</param>
/// <param name="SalesmanUserId">Reference to a user object representing the salesman.</param>
/// <param name="KbPaymentTemplateId">Reference to the payment template (read-only).</param>
/// <param name="TemplateSlug">Reference to a document template slug.</param>
/// <param name="Title">Free-form purchase order title.</param>
/// <param name="Header">Free-text header printed on top of the purchase order.</param>
/// <param name="Footer">Free-text footer printed below the positions.</param>
/// <param name="MwstType">VAT/MwSt. handling flag — one of <c>included</c>, <c>excluded</c>, or <c>exempt</c>.</param>
/// <param name="MwstIsNet">When <see langword="true"/> and <see cref="MwstType"/> is <c>excluded</c>, the total excludes taxes.</param>
/// <param name="IsCompactView">Whether the document uses compact view rendering.</param>
/// <param name="ShowPositionTaxes">Whether per-position taxes are shown on the printed document.</param>
/// <param name="IsValidFrom">Order validity start in Bexio's <c>yyyy-MM-dd</c> format.</param>
/// <param name="IsValidUntil">Order validity end in Bexio's <c>yyyy-MM-dd</c> format.</param>
/// <param name="IsValidTo">Alias for <c>is_valid_until</c> populated by some Bexio responses.</param>
/// <param name="DeliveryAddressType">Delivery address selector — one of <c>contact_address</c> or <c>manual</c>.</param>
/// <param name="ContactAddressManual">Manually overridden contact address. Newlines are escaped as <c>\\n</c>.</param>
/// <param name="DeliveryAddressManual">Manually overridden delivery address. Newlines are escaped as <c>\\n</c>.</param>
/// <param name="NbDecimalsAmount">Maximum number of decimal digits to display for amounts.</param>
/// <param name="NbDecimalsPrice">Maximum number of decimal digits to display for prices.</param>
/// <param name="KbItemStatusId">Read-only status id (22 Draft, 23 Open, 24 Partly, 25 Done, 26 Canceled).</param>
/// <param name="TermsOfPaymentText">Free-form text appended below the terms of payment.</param>
/// <param name="Reference">Caller-supplied reference (e.g. the originating quote number).</param>
/// <param name="ApiReference">Caller-supplied reference accessible only via the API.</param>
/// <param name="Mail">Mail address of the supplier company.</param>
/// <param name="ViewedByClientAt">Timestamp when the purchase order was first opened by the recipient (read-only).</param>
/// <param name="TotalRoundingDifference">Rounding difference applied to the total (read-only).</param>
/// <param name="DateFormat">Date format string used by the rendered document.</param>
/// <param name="CreatedAt">Creation date of the purchase order (read-only).</param>
/// <param name="UpdatedAt">Timestamp of the last update (read-only).</param>
public sealed record PurchaseOrder(
    [property: JsonPropertyName("id")] int Id,
    [property: JsonPropertyName("document_nr")] string? DocumentNr = null,
    [property: JsonPropertyName("contact_id")] int? ContactId = null,
    [property: JsonPropertyName("user_id")] int? UserId = null,
    [property: JsonPropertyName("currency_id")] int? CurrencyId = null,
    [property: JsonPropertyName("language_id")] int? LanguageId = null,
    [property: JsonPropertyName("bank_account_id")] int? BankAccountId = null,
    [property: JsonPropertyName("payment_type_id")] int? PaymentTypeId = null,
    [property: JsonPropertyName("logopaper_id")] int? LogopaperId = null,
    [property: JsonPropertyName("contact_sub_id")] int? ContactSubId = null,
    [property: JsonPropertyName("project_id")] int? ProjectId = null,
    [property: JsonPropertyName("salesman_user_id")] int? SalesmanUserId = null,
    [property: JsonPropertyName("kb_payment_template_id")] int? KbPaymentTemplateId = null,
    [property: JsonPropertyName("template_slug")] string? TemplateSlug = null,
    [property: JsonPropertyName("title")] string? Title = null,
    [property: JsonPropertyName("header")] string? Header = null,
    [property: JsonPropertyName("footer")] string? Footer = null,
    [property: JsonPropertyName("mwst_type")] string? MwstType = null,
    [property: JsonPropertyName("mwst_is_net")] bool? MwstIsNet = null,
    [property: JsonPropertyName("is_compact_view")] bool? IsCompactView = null,
    [property: JsonPropertyName("show_position_taxes")] bool? ShowPositionTaxes = null,
    [property: JsonPropertyName("is_valid_from")] string? IsValidFrom = null,
    [property: JsonPropertyName("is_valid_until")] string? IsValidUntil = null,
    [property: JsonPropertyName("is_valid_to")] string? IsValidTo = null,
    [property: JsonPropertyName("delivery_address_type")] string? DeliveryAddressType = null,
    [property: JsonPropertyName("contact_address_manual")] string? ContactAddressManual = null,
    [property: JsonPropertyName("delivery_address_manual")] string? DeliveryAddressManual = null,
    [property: JsonPropertyName("nb_decimals_amount")] int? NbDecimalsAmount = null,
    [property: JsonPropertyName("nb_decimals_price")] int? NbDecimalsPrice = null,
    [property: JsonPropertyName("kb_item_status_id")] int? KbItemStatusId = null,
    [property: JsonPropertyName("terms_of_payment_text")] string? TermsOfPaymentText = null,
    [property: JsonPropertyName("reference")] string? Reference = null,
    [property: JsonPropertyName("api_reference")] string? ApiReference = null,
    [property: JsonPropertyName("mail")] string? Mail = null,
    [property: JsonPropertyName("viewed_by_client_at")] string? ViewedByClientAt = null,
    [property: JsonPropertyName("total_rounding_difference")] decimal? TotalRoundingDifference = null,
    [property: JsonPropertyName("date_format")] string? DateFormat = null,
    [property: JsonPropertyName("created_at")] string? CreatedAt = null,
    [property: JsonPropertyName("updated_at")] string? UpdatedAt = null
);
